### ISSUE TITLE
V1 Milestone issues

### ISSUE THREAD

**Issue by Igosuki** [Adikteev/cuttle#2]
- [ ] Take out sql migrations from connection code
- [ ] Check pooling
- [ ] Add metrics on everything + reporter
- [ ] Pretty print graphs in console or stdout
- [ ] Scala.js visual react component library
